# Generated by Django 3.0.8 on 2020-08-25 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200824_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='starting_price',
            new_name='price',
        ),
    ]
