# Generated by Django 3.0.8 on 2020-08-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200824_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='creationdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bids',
            name='date_bid',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(),
        ),
    ]
