# Generated by Django 3.0.8 on 2020-08-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200824_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
